name: Deploy to Vercel

on:
  push:
    branches:
      - main  # deploy on main branch push

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # <-- use your project name here
          working-directory: ./               # adjust if your project is in a subfolder
          github-comment: true
          vercel-args: '--prod'               # optional for production deploy
